<?xml version="1.0"?>
<package format="3">
  <name>istk_lib</name>
  <version>0.0.1</version>
  <description>ISTK robot launch and calibration utilities.</description>

  <maintainer email="yaromir.khrykin@gmail.com">yaromir</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <exec_depend>sllidar_ros2</exec_depend>
  <exec_depend>dual_laser_merger</exec_depend>
  <exec_depend>multi_lidar_calibration</exec_depend>

  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
