left_to_right:
  parent_frame: laser_left
  child_frame: laser_right
  translation:
    x: -0.7914579
    y: -0.33968899999999996
    z: 0.0
  rotation_rpy:
    roll: 0.0
    pitch: 0.0
    yaw: -1.0794503999999996
base_frame: base_link
