shape:
  length: 1.760           # m, overall length l1
  width: 0.775            # m, overall width b1
  base_to_rear: 0.880     # m, if base is near geometric center
  circles_count: 9        # qnt, long body approximation

wheel_base:
  length: 1.261           # m, wheelbase y
  width: 0.001            # m, virtual single steering wheel; avoid exact zero
  base_to_rear: 0.6305    # m, if base is at wheelbase center

wheel:
  radius: 0.125           # m, drive wheel diameter 250 mm / 2
  width: 0.070            # m, drive wheel width 70 mm

lidar:
  angle_min: 0.0          # deg
  angle_max: 360.0        # deg
  angle_increment: 0.1125 # deg
  range_min: 0.05         # m
  range_max: 30.0         # m

limits:
  steering: { inner: 38.2, outer: 38.2 } # deg, bicycle-equivalent
  max_abs_curvature: 0.625               # 1/m, 1 / 1.6 m min turning radius
  steering_velocity: 2.0                 # rad/s, leave conservative
  velocity: { min: -0.5, max: +1.9 }     # m/s, 7 km/h ~= 1.94 m/s
  max_acceleration: 0.5                  # m/s^2, conservative
  max_deceleration: 1.0                  # m/s^2, conservative

# Motor to differential ratio. See docs/gearbox.md for more info.
gear_ratio: 0.08421
servo_home_angles: { left: 89, right: 96 }  # deg

tf_static:
  - frame_id: "base"
    child_frame_id: "lidar_link"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "base"
    child_frame_id: "camera_link"
    translation: { x: 0.25, y: 0.05, z: -0.04 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "base"
    child_frame_id: "rear_axle"
    translation: { x: 0.2025, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "base"
    child_frame_id: "rear_axle_fix"
    translation: { x: -0.2025, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "camera_link"
    child_frame_id: "camera_gyro_frame"
    translation: { x: -0.01602, y: -0.03022, z: 0.0074 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "camera_gyro_frame"
    child_frame_id: "camera_gyro_optical_frame"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: -0.5, y: 0.5, z: -0.5, w: 0.5 }

  - frame_id: "camera_gyro_optical_frame"
    child_frame_id: "camera_imu_optical_frame"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "camera_link"
    child_frame_id: "camera_depth_frame"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "camera_depth_frame"
    child_frame_id: "camera_depth_optical_frame"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: -0.5, y: 0.5, z: -0.5, w: 0.5 }

  # specific frame names for simulator

  - frame_id: "base"
    child_frame_id: "rplidar_s2::lidar_link"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "camera_gyro_optical_frame"
    child_frame_id: "d455::camera_imu_optical_frame"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  # truck parts

  - frame_id: "base"
    child_frame_id: "body"
    translation: { x: 0.0, y: 0.0, z: 0.0 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "base"
    child_frame_id: "front_left_wheel"
    translation: { x: -0.2025, y: -0.11168, z: 0.01329 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "base"
    child_frame_id: "front_right_wheel"
    translation: { x: 0.2025, y: -0.11168, z: 0.01329 }
    rotation: { x: 0.0, y: 0.0, z: 1.0, w: 0.0 }

  - frame_id: "base"
    child_frame_id: "rear_left_wheel"
    translation: { x: 0.2025, y: -0.11168, z: 0.01329 }
    rotation: { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }

  - frame_id: "base"
    child_frame_id: "rear_right_wheel"
    translation: { x: -0.2025, y: -0.11168, z: 0.01329 }
    rotation: { x: 0.0, y: 0.0, z: 1.0, w: 0.0 }
