readingDataPointsFilters:
   - RandomSamplingDataPointsFilter

referenceDataPointsFilters:
   - SamplingSurfaceNormalDataPointsFilter

matcher:
 KDTreeMatcher:
   knn: 1
   epsilon: 3.16

outlierFilters:
   - TrimmedDistOutlierFilter:
      ratio: 0.85
   - RobustOutlierFilter:
      robustFct: cauchy
      tuning: 1.0
      distanceType: point2plane

errorMinimizer:
   PointToPlaneErrorMinimizer:
      force2D: 1

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 40
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 3

inspector:
   NullInspector

logger:
   FileLogger
