; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4
framework = arduino
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
board_build.partitions = partitions_32mb.csv
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
monitor_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_5B5E134448-if00
upload_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_5B5E134448-if00
lib_deps = 
	robtillaart/MCP4725@^0.4.3
	simplefoc/SimpleFOCDrivers@^1.0.9
	hideakitai/Packetizer@^0.8.3
